import React from "react";
import { DistanceHistogram, LiveMechanismReplay, RadiusFrontier } from "./ResearchEvidence";
import type { EvidenceIndex, EvidenceSyncState, ExperimentEvidence } from "../types/evidence";

function value(v: unknown) { return v === undefined || v === null || v === "" ? "UNAVAILABLE" : String(v); }
function ExperimentCard({ experiment }: { experiment: ExperimentEvidence }) {
  const metricEntries = Object.entries(experiment.metrics ?? {});
  return <article className="experiment-card"><div className="experiment-top"><span>{experiment.id}</span><em>{experiment.status}</em></div><h3>{experiment.title}</h3><p>{experiment.claim_scope ?? "Claim scope unavailable."}</p><div className="experiment-meta"><span>{experiment.kind}</span><span>{experiment.coverage ?? "UNKNOWN COVERAGE"}</span></div>{metricEntries.length > 0 && <dl>{metricEntries.map(([key, metric]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{typeof metric === "object" ? JSON.stringify(metric) : String(metric)}</dd></div>)}</dl>}{(experiment.warnings ?? []).map((warning) => <div className="warning" key={warning}>{warning}</div>)}</article>;
}

export function EvidenceOverview({ index, sync, error }: { index: EvidenceIndex | null; sync: EvidenceSyncState; error: string | null }) {
  const dataset = index?.dataset; const experiments = index?.experiments ?? []; const radius = experiments.find((item) => item.metrics?.radius_hits); const live = experiments.find((item) => item.id === "PRISM-12" || item.kind === "LIVE_MECHANISM");
  return <section className="product-section evidence-section" id="evidence"><div className="section-head"><span className="section-index">04</span><div><p className="eyebrow">Evidence</p><h2>The product carries its claim boundary.</h2><p className="section-copy">Dataset, retrieval, graph structure, live mechanism, controls, causal effect, and reproduction belong in the product—not in an appendix.</p></div></div><div className="provenance-bar"><div><span>Source state</span><strong>{sync}</strong></div><div><span>Repository</span><strong>{value(index?.repository)}</strong></div><div><span>Ref</span><strong>{value(index?.ref)}</strong></div><div><span>Commit</span><strong>{index?.commit?.slice(0, 12) ?? "UNAVAILABLE"}</strong></div></div>{sync === "LOADING" && <div className="evidence-empty"><span>LOADING</span><h3>Reading canonical evidence index…</h3></div>}{sync === "UNAVAILABLE" && <div className="evidence-empty"><span>EVIDENCE SOURCE UNAVAILABLE</span><h3>No canonical evidence index is available to the product.</h3><p>{error ?? "The interface remains usable without fabricating evidence."}</p></div>}{index && <><div className="dataset-grid"><div className="dataset-title"><span>DATASET</span><h3>{value(dataset?.benchmark)}</h3><p>{value(dataset?.tier)} / {value(dataset?.coverage)} / {dataset?.multimodal === true ? "multimodal" : dataset?.multimodal === false ? "single modality" : "UNAVAILABLE"}</p></div>{[["Questions", dataset?.questions], ["Trajectories", dataset?.trajectories], ["Haystack questions", dataset?.haystack_questions], ["Runtime screenshot links", dataset?.runtime_screenshot_links], ["Validation", dataset?.validation]].map(([label, metric]) => <div className="dataset-stat" key={String(label)}><span>{label}</span><strong>{value(metric)}</strong></div>)}</div><div className="commit-strip"><div><span>Benchmark code</span><strong>{value(dataset?.benchmark_code_commit)}</strong></div><div><span>Dataset revision</span><strong>{value(dataset?.dataset_revision)}</strong></div><div><span>HydraDB</span><strong>{value(dataset?.hydradb_commit)}</strong></div></div></>}<div className="research-grid"><RadiusFrontier experiment={radius} /><DistanceHistogram experiment={radius} /><LiveMechanismReplay experiment={live} /></div>{index && <div className="experiment-list">{experiments.length ? experiments.map((experiment) => <ExperimentCard key={experiment.id} experiment={experiment} />) : <div className="evidence-empty compact"><span>EXPERIMENTS</span><h3>NOT_RUN / UNAVAILABLE</h3><p>The index contains no experiment objects yet.</p></div>}</div>}</section>;
}
