import type { DatasetEvidence, EvidenceIndex, EvidenceStatus, ExperimentEvidence } from "../types/evidence.js";
const STATUS = new Set<EvidenceStatus>(["IMPLEMENTED", "TESTED", "DEPLOYED", "SIMULATED", "PROPOSED", "UNKNOWN", "NOT_RUN"]);
function asRecord(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function asString(value: unknown): string | undefined { return typeof value === "string" ? value : undefined; }
function asNumber(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) ? value : undefined; }
function asBool(value: unknown): boolean | undefined { return typeof value === "boolean" ? value : undefined; }
export function parseEvidenceIndex(input: unknown): EvidenceIndex {
  const root = asRecord(input); if (!root) throw new Error("Evidence index is not an object");
  const schemaVersion = asString(root.schema_version); if (!schemaVersion) throw new Error("Evidence index is missing schema_version");
  const datasetRaw = asRecord(root.dataset);
  const dataset: DatasetEvidence | undefined = datasetRaw ? { benchmark: asString(datasetRaw.benchmark), tier: asString(datasetRaw.tier), coverage: asString(datasetRaw.coverage) as DatasetEvidence["coverage"], multimodal: asBool(datasetRaw.multimodal), questions: asNumber(datasetRaw.questions), trajectories: asNumber(datasetRaw.trajectories), haystack_questions: asNumber(datasetRaw.haystack_questions), runtime_screenshot_links: asNumber(datasetRaw.runtime_screenshot_links), validation: asString(datasetRaw.validation), benchmark_code_commit: asString(datasetRaw.benchmark_code_commit), dataset_revision: asString(datasetRaw.dataset_revision), hydradb_commit: asString(datasetRaw.hydradb_commit) } : undefined;
  const experiments: ExperimentEvidence[] = Array.isArray(root.experiments) ? root.experiments.flatMap((value) => { const item = asRecord(value); if (!item) return []; const id = asString(item.id); const title = asString(item.title); const status = asString(item.status); if (!id || !title || !status) return []; return [{ id, title, kind: asString(item.kind) ?? "UNKNOWN", status: STATUS.has(status as EvidenceStatus) ? status as EvidenceStatus : "UNKNOWN", coverage: asString(item.coverage) as ExperimentEvidence["coverage"], ablation_stage: asString(item.ablation_stage) as ExperimentEvidence["ablation_stage"], claim_scope: asString(item.claim_scope), result_path: asString(item.result_path), report_path: asString(item.report_path), checksums_path: asString(item.checksums_path), metrics: asRecord(item.metrics) ?? {}, warnings: Array.isArray(item.warnings) ? item.warnings.filter((x): x is string => typeof x === "string") : [] }]; }) : [];
  return { schema_version: schemaVersion, generated_at: asString(root.generated_at), repository: asString(root.repository), ref: asString(root.ref), commit: asString(root.commit), dataset, experiments, latest: asRecord(root.latest) ?? {} };
}
